language: java

addons:
  sonarcloud:
    organization: "pjvilloud-github"

script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.organization=pjvilloud-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=49be15836156a9b352f356926452dc5aaad157c9 -Dsonar.projectKey=com.ipiecoles.java.java340:ipi-java-350-eval -Dsonar.branch=master


