language: java

addons:
  sonarcloud:
    organization: "pjvilloud-github"

script: mvn sonar:sonar -Dsonar.organization=pjvilloud-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=49be15836156a9b352f356926452dc5aaad157c9